pipeline {
    agent any

    tools {
        // Installer la version de Maven configurée comme "M3" et l'ajouter au chemin.
        maven "M2-HOME"
    }

    stages {
        stage('Checkout') {
            steps {
                // Récupérer le code de la branche spécifique depuis votre dépôt
                git branch: 'djmal-yosra', url: 'https://github.com/yossraa123/ski.git'
            }
        }
        
        stage('Build') {
            steps {
                // Se déplacer dans le répertoire où se trouve le pom.xml
                dir('gestion-station-ski') {
                    // Lister les fichiers pour s'assurer que pom.xml est présent
                    sh 'ls -la'
                    // Exécuter Maven pour nettoyer et empaqueter le projet
                    sh 'mvn -Dmaven.test.failure.ignore=true clean package'
                }
            }
        }

    }
}
